include $(REPODIR)/Rules.mk

content:
	mkdir -p content/bin
	mkdir -p content/etc/opkg
	cp $(ROOTDIR)/user/opkg/opkg-649/src/opkg-cl content/bin/opkg-cl
	cp $(ROOTDIR)/vendors/Elster/uwic/opkg.conf content/etc/opkg/opkg.conf
