#!/bin/sh

mount -t ramfs ramfs /tmp
mount -t proc proc /proc

mount -t cramfs /dev/mtdblock0 /etc/romdisk
insert-passphrase /etc/romdisk/key
mount -t ecryptfs /etc/.secret /etc/secret -o rw,ecryptfs_sig=0000000000000001,ecryptfs_key_bytes=16,ecryptfs_cipher=aes

rm -rf /var/tmp/*

uci -D_ -e show config > /tmp/conf
. /tmp/conf
/bin/rm /tmp/conf

[ "$config_kernel_have_sysfs" = "1" ] && /bin/mount -t sysfs sys /sys
[ "$config_kernel_have_devpts" = "1" ] && /bin/mount -t devpts devpts /dev/pts

mkdir -p /tmp/run

for i in /etc/rc.d/S*; do
	. $i
done
