#!/bin/sh

if [ -z "$system_syslog" ]; then
	uci -D_ -e show system.syslog > /tmp/syslog_conf
	. /tmp/syslog_conf
	rm /tmp/syslog_conf
fi

ARGS="-n"

if [ -n "$system_klog_level" ]; then
	ARGS="$ARGS -c $system_klog_level"
fi

start-stop-daemon -p /var/run/klogd.pid -x klogd -b -m -S -- $ARGS