#!/bin/sh

if [ -z "$system_syslog" ]; then
	uci -D_ -e show system.syslog > /tmp/syslog_conf
	. /tmp/syslog_conf
	rm /tmp/syslog_conf
fi

ARGS="-n -S"

if [ -n "$system_syslog_remote" ]; then
	ARGS="$ARGS -R $system_syslog_remote -L"
fi

if [ -n "$system_syslog_level" ]; then
	ARGS="$ARGS -l $system_syslog_level"
fi

start-stop-daemon -p /tmp/run/syslogd.pid -x syslogd -b -m -S -- $ARGS