#!/bin/sh

if [ -z "$network" ]; then
	uci -D_ -e show network > /tmp/network_conf
	. /tmp/network_conf
	rm /tmp/network_conf
fi

touch /etc/resolv.conf
touch /etc/hosts

if [ -n "$network_lo" ]; then
	ifconfig $network_lo_ifname $network_lo_ipaddr netmask $network_lo_netmask
	echo "$network_lo_ipaddr localhost" >> /etc/hosts
fi

if [ -n "$network_lan" ]; then
	if [ "$network_lan_proto" = "static" ]; then
		ifconfig $network_lan_ifname down
		ifconfig $network_lan_ifname hw ether $network_lan_macaddr
		ifconfig $network_lan_ifname up
		ifconfig $network_lan_ifname $network_lan_ipaddr netmask $network_lan_netmask
	fi

	if [ -n "$network_lan_dns" ]; then
		echo "nameserver $network_lan_dns" >> /etc/resolv.conf
	fi
fi

if [ -n "$network_wan" ]; then
	start-stop-daemon -p /var/run/pppd0.pid -x pppd -b -S -- call gprs
else
	if [ -n "$network_route" ]; then
		route add $network_route_target gw $network_route_gateway metric $network_route_metric dev $network_route_ifname
	fi
fi