#!/bin/sh

if [ -z "$network" ]; then
	cfg network > /tmp/network_conf
	. /tmp/network_conf
	rm /tmp/network_conf
fi

touch /etc/resolv.conf
touch /etc/hosts

if [ "$network_lo_enable" == "yes" ]; then
	ifconfig lo $network_lo_ipaddr netmask $network_lo_netmask
	echo "$network_lo_ipaddr localhost" >> /etc/hosts
fi

if [ "$network_eth0_enable" == "yes" ]; then
	if [ "$network_eth0_proto" = "static" ]; then
		ifconfig eth0 down
		ifconfig eth0 hw ether $network_eth0_macaddr
		ifconfig eth0 up
		ifconfig eth0 $network_eth0_ipaddr netmask $network_eth0_netmask
		if [ -n "$network_eth0_gateway" -a "$network_eth0_gateway" != "0.0.0.0" ]; then
			route add default gw $network_eth0_gateway metric 100 dev eth0
		fi
	fi
fi

if [ -n "$network_dns_nameserver" -a "$network_dns_nameserver" != "0.0.0.0" ]; then
	echo "nameserver $network_dns_nameserver" >> /etc/resolv.conf
fi

if [ "$network_ppp0_enable" == "yes" ]; then
  echo "ABORT   'BUSY'"        > /etc/ppp/chat/gprs
  echo "ABORT   'NO CARRIER'" >> /etc/ppp/chat/gprs
  echo "ABORT   'ERROR'"      >> /etc/ppp/chat/gprs
  echo "''      AT"           >> /etc/ppp/chat/gprs
  echo "OK      AT#PORTCFG=3" >> /etc/ppp/chat/gprs
  echo "OK      AT+CGDCONT=1,\"$network_ppp0_proto\",\"$network_ppp0_apn\",\"$network_ppp0_addr\",$network_ppp0_d_comp,$network_ppp0_h_comp" >> /etc/ppp/chat/gprs
  echo "OK      ATD$network_ppp0_dial"  >> /etc/ppp/chat/gprs
  echo "CONNECT"              >> /etc/ppp/chat/gprs

	start-stop-daemon -p /tmp/run/pppd.pid -x pppd -b -m -S -- call gprs
fi