#!/bin/sh

/bin/uci -D_ -e show config.clock > /tmp/clock_conf
. /tmp/clock_conf
/bin/rm /tmp/clock_conf

date -s "$config_clock_default"
ntpclient -s -i "$config_clock_ntptimeout" -g 10000 -h "$config_clock_ntpserver" -c 3