include $(REPODIR)/Rules.mk

content:
	mkdir -p content/usr/local/share/lua/5.1
	mkdir -p content/bin
	cp $(ROMFSDIR)/usr/local/share/lua/5.1/mgate.lua content/usr/local/share/lua/5.1/mgate.lua
	cp $(ROMFSDIR)/bin/mgate content/bin/mgate
