#!/bin/sh

if [ -z "$system_clock" ]; then
	uci -D_ -e show system.clock > /tmp/clock_conf
	. /tmp/clock_conf
	rm /tmp/clock_conf
fi

date -s "$system_clock_default"
/bin/start-stop-daemon -x /bin/htpdate -p /var/run/htpdate.pid -m -b -S -- -D -s -4 "$system_clock_timeserver"